### ISSUE TITLE
Add "pxGrid approve-node

### ISSUE THREAD

**Issue by cunningr** [falkowich/ise#142]
https://developer.cisco.com/docs/identity-services-engine/#!pxgrid-node/approve-node

this would help us with our DNA Workflows project; https://github.com/cunningr/dna_workflows

**Comment by falkowich** [comment]
This is doable indeed.
Have you looked at it and have a PR?

Or should we add it to our todo?

--
Regards Falk

**Comment by cunningr** [comment]
Actually I found out that my use case is already covered elsewhere so this would no longer be needed from my side.  I'll close the issue if that is ok?
