### ISSUE TITLE
Pages and Sizes 

### ISSUE THREAD

**Issue by anousonevongsouvanTR** [falkowich/ise#143]
Hello, I am not sure if this is an issue or not, but I have a need to query around 2000 devices.  There seems to be a page/size option that you can specify:
device_list_1 = ise.get_devices(size=20, page=1)['response']

I believe the max size is 100, so to get to 2000, I'd make requests for 20 pages.  Is there another mechanism to follow the next page?
For example, using Postman to make a request, I see this at the end of the output:

"nextPage": {
      "rel": "next",
      "href": "https://x.x.x.x:9060/ers/config/networkdevice?size=45&page=2",
      "type": "application/json"

However, in the output of using ise.get request, the output never shows the next page.    

Thanks

**Comment by falkowich** [comment]
Hi,

The ['response'] is only the "actual" response of (in this case) the devices.
And the full response from `device_list_1 = ise.get_devices(size=2, page=1)` should be a json:
```python
{
'success': True, 
'response': [('device01', 'ffffc0-a9c0-11e7-b7ac-005056837239'), ('device02', 'ffff60-a9c0-11e7-b7ac-005056837239')], 
'error': '', 
'nextPage': '2', 
'total': 927
}
```
Does that explanation make sense? :)

--
Regards Falk

**Comment by anousonevongsouvanTR** [comment]
ah thank you for that explanation.  I'll close this.
