### ISSUE TITLE
Multi version support?

### ISSUE THREAD

**Issue by steffenschumacher** [falkowich/ise#144]
Hey,
I’m porting 2.1 to 2.4 - will this work on both?

**Comment by falkowich** [comment]
Hi, 
We have used it extensively on ISE 2.4 but I haven't tried it on 2.1. 
A few of the latest additions is with TrustSec objects, only works with 2.4+.

But all the basic stuff "should" be working, it depends somewhat how much the ERS API was change from 2.1 -> 2.2 when we started using and maintaining this fork.

--
Regards Falk
